-- Athlevo acquisition and activation analytics taxonomy.
--
-- Run manually after review. This file is not applied by the application.
-- It only widens activation_events.event_name; no product or user data is
-- updated, reset, or deleted.

alter table public.activation_events
  drop constraint if exists activation_events_event_name_check;

alter table public.activation_events
  add constraint activation_events_event_name_check
  check (event_name in (
    'landing_viewed',
    'signup_cta_clicked',
    'auth_screen_viewed',
    'google_signup_clicked',
    'email_signup_clicked',
    'login_clicked',
    'in_app_browser_signup_blocked',
    'external_signup_link_copied',
    'external_signup_continuation_viewed',
    'registration_completed',
    'onboarding_started',
    'onboarding_completed',
    'data_connection_started',
    'data_connection_completed',
    'provider_skipped',
    'first_value_viewed',
    'activation_completed',
    'signup_failed',
    'onboarding_failed',
    'data_connection_failed',
    'activation_failed',
    'free_account_created',
    'free_limit_reached',
    'premium_feature_viewed',
    'upgrade_clicked',
    'upgrade_sheet_viewed',
    'checkout_started',
    'checkout_failed',
    'subscription_activated',
    'account_created',
    'email_verified',
    'athlete_onboarding_started',
    'athlete_onboarding_completed',
    'wearable_setup_started',
    'sync_account_step_viewed',
    'wearable_provider_step_viewed',
    'wearable_connection_succeeded',
    'wearable_connection_failed',
    'first_sync_started',
    'first_activity_imported',
    'activity_imported',
    'first_workout_analysis_viewed',
    'plan_generation_started',
    'first_plan_generated',
    'plan_generation_failed',
    'coach_opened',
    'first_coach_message_sent',
    'coach_message_submitted',
    'coach_message_completed',
    'coach_weekly_limit_reached',
    'coach_request_failed',
    'adaptive_plan_reviewed',
    'adaptive_plan_applied',
    'readiness_prompt_shown',
    'readiness_prompt_dismissed',
    'readiness_check_completed',
    'app_returned',
    'app_session_started',
    'primary_tab_viewed',
    -- retained legacy values for existing rows and older clients
    'strava_connected',
    'first_sync_completed',
    'first_plan_created',
    'first_workout_viewed',
    'first_workout_completed',
    'first_coach_message',
    'app_opened',
    'signup_started',
    'signup_completed',
    'profile_completed',
    'connect_step_viewed',
    'intervals_connected',
    'activities_detected',
    'initial_sync_started',
    'initial_sync_completed',
    'dashboard_opened',
    'sync_failed',
    'no_activities',
    'checkout_opened',
    'paid_subscription_activated',
    'coach_upgrade_sheet_viewed'
  ));
